#! /usr/bin/env sh

# Script will init a empty script file in the ~/scripts folder 
# add the shebang and make it executable

SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"
SCRIPT_LANG=${2:-sh}


if [ -f $SCRIPT_FILE ]; then 
    code $SCRIPT_FILE
else
    echo "#! /usr/bin/env $SCRIPT_LANG" > $SCRIPT_FILE
    chmod +x $SCRIPT_FILE
    eval $EDITOR $SCRIPT_FILE
fi

 



