#! /usr/bin/env sh

# Script will init a empty script file in the ~/scripts folder 
# add the shebang and make it executable
# assumes vscode is installed and is in path

SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [ -f $SCRIPT_FILE ]; then 
    code file already exist
else
    echo '#! /usr/bin/env sh' > $SCRIPT_FILE
    chmod +x $SCRIPT_FILE
    code $SCRIPT_FILE
fi

 



